route_planner.settings:
  type: mapping
  label: Settings
  mapping:
    route_planner_map_height:
      type: string
    route_planner_map_width:
      type: string
    route_planner_map_zoom:
      type: integer
    route_planner_map_defaultui:
      type: boolean
    route_planner_map_zoomcontrol:
      type: boolean
    route_planner_map_scrollwheel:
      type: boolean
    route_planner_map_maptypecontrol:
      type: boolean
    route_planner_map_scalecontrol:
      type: boolean
    route_planner_map_draggable:
      type: boolean
    route_planner_map_doubbleclick:
      type: boolean
    route_planner_map_streetviewcontrol:
      type: boolean
    route_planner_map_overviewmapcontrol:
      type: boolean
    route_planner_address:
      type: string
    route_planner_address_end:
      type: boolean
    route_planner_unitsystem:
      type: boolean
